# Generated by Django 4.0.4 on 2022-04-26 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_user_id_user_uuid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='BaseUser',
        ),
    ]
